name: Log action
on:
  label:
    types: [created]
  issues:
    types: [opened]
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger - ${{ github.event_name }}, user - ${{ github.actor }}, date - `date`"
